### ISSUE TITLE
`Data.streamfrom` only has access to first row of query

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaDB/ODBC.jl#162]
After constructing an `ODBC.Source`, when using `Data.streamfrom(src, Data.Field, ...)` on anything past the first row results in a bounds error.  Evidently, the source only contains the first row of the query and does not pull additional rows upon request.  Looking into this now.

**Comment by quinnj** [comment]
When the `ODBC.Source` is constructed, it determines how many rows it can fetch at a time (the `rowset` variable in the `ODBC.Source` constructor); for some databases, that means only 1 row at a time. But each call to `fetch!` sets the `rowsfetched` `Ref{Int}` `ODBC.Source` field, so that should indicate how many rows are available.

**Comment by ExpandingMan** [comment]
Ok, I think I see what's happening how.  I don't think there's anything wrong with `fetch!`, the error is being thrown from [here](https://github.com/JuliaDB/ODBC.jl/blob/master/src/Source.jl#L329).  Apparently `rowoffset` is being set incorrectly...

**Comment by quinnj** [comment]
It's possible there's a bug where that's getting set wrong.

**Comment by ExpandingMan** [comment]
Yup, looking into it now.  Will make a PR if I'm able to fix it.

**Comment by ExpandingMan** [comment]
However, I can't seem to figure out what `fetch!` is supposed to do exactly.  In my case it doesn't seem to be doing much of anything.

**Comment by quinnj** [comment]
> What's quite confusing is that Data.Column streams one row at a time, dumping the previous rows, pulling the next row when you request the last column

Again, this isn't strictly true; it depends on the database. Many databases support the fetching of rows in > 1 batches, so typically, `rowset` is > 1 and when `fetch!` is called, an entire new batch of rows is fetched from the database.

ODBC is unique in that it's actually a true streaming situation in that the data is fetched incrementally. `rowsfetched` holds the # of rows that were actually fetched on each call to `fetch!` which will never be > `rowset`, but could be less.

`rowoffset` is used because when calling `Data.streamfrom` for `Data.Field`, as a user, I want row 25, but for the `ODBC.Source`, it might have a `rowset` size of 5, which means 5 rows at a time are fetched from the DB. So `ODBC.Source` needs to remember as it streams rows sequentially, how many rows it has already processed in order to provide the correct row next from it's local batch.

> What's quite confusing is that Data.Column streams one row at a time, dumping the previous rows, pulling the next row when you request the last column.

I don't see why this is terrible, it just means that `ODBC.Source` is a true streaming source, i.e. it's not going to hold on to the entire dataset permanently, that's the sink's job. 

In response to your original issue/question, `ODBC.Source` currently requires that the data be requested/accessed sequentially: if streaming via `Data.Field`, you must start at row 1, and stream the columns for each row; for `Data.Column`, each column can be requested, understanding that there may be multiple "batches" of columns streamed (i.e. it doesn't always suffice to just call `Data.streamfrom` once for each column). In both cases, the current trigger to fetch a new batch is accessing the last column; this probably isn't ideal because it prevents the situation you've discussed elsewhere when a user wants to only stream a sub-select portion of columns. For ODBC, I don't see this as quite as urgent, however, since you can almost always just modify your original query to ensure you only select the columns you desire in the final dataset.

**Comment by ExpandingMan** [comment]
Thanks for your detailed response.

It would probably be helpful if I described what I'm trying to do: I want to pull batches (datasets consisting of elements from pre-defined row, column locations) efficiently and using the `DataStreams` interface and using only a single query.  Presumably these will typically be large (~ 1GB) batches in practice.

As I understand it, currently `DataStreams` only allows you to pull either entire columns (`Data.Column`) or individual fields (`Data.Field`).  Currently the program that I have doing the pulling into batches is using `Data.Field` on one column at a time (in general, I don't want to fetch every row of a column).  Since in most data sources data is stored by column (because columns have a well-defined type), this seems like the best approach.  However, I'm currently rather concerned that this is quite inefficient in `ODBC` because it would require excessive "scrolling" (and I'm still not entirely clear about at what point the actual I/O occurs).  Maybe I'm just being paranoid and not grasping things fully, and what I'm trying to do will work just fine once the `Data.Field` bug is fixed.  Another possibility is that I might have to make a second implementation of my batching-transform program for sources that stream in a row-based way.

I'll post again, and hopefully make a fix once I understand ODBC better.

**Comment by quinnj** [comment]
> Also, the reason I was suggesting that it's a problem that Data.Columns streams one row at a time is that it seems different from the behavior of other Data.Sources, so from a DataStreams users perspective it is quite unexpected.

Unfortunately, this is a limitation of ODBC, and more specifically, of the ODBC driver for the specific database you're working with. As I said, most databases are able to stream batches of rows at a time (MySQL, PostgreSQL, etc.), others can't provide a clear answer to the question "how many rows will be in the result of this query" and so only one row is fetched at a time (which is certainly less efficient than fetching batches of rows at a time). 

If I were you, I wouldn't worry too much about trying to do the row filtering/selecting at the DataStreams level. Personally, I would do `Data.Column` streaming and perform the row-filtering/selecting once I've extracted an entire column. The max # of rows you'll ever get from that (given the DB supports it), is 65535 (`ODBC.API.MAXFETCHSIZE`), so nothing crazy large.

**Comment by ExpandingMan** [comment]
Hmm... I dislike SQL more and more every day.  You would think that an indexing operation like `column[start_row:end_row]` would be a completely trivial thing and that every database would want to support that in as efficient a way as possible.  It always seems like the best solution is just to take a huge chunk of a database and store it somewhere else in a better format (I've had great success doing things this way with `DataStreams` and Feather after implementing a true `streamfrom` `Field` method), which I suppose is exactly what you've designed this package to do.
