### ISSUE TITLE
Querying a SQL Server NTEXT field hangs my machine (ODBC 0.3.8 with Julia 0.3.0-prerelease)

### ISSUE THREAD

**Issue by dierickx3** [JuliaDB/ODBC.jl#53]
Even just querying a 5-row table via a contrived query such as "SELECT MyNTextField FROM dbo.TestTable" where the MyNtextField holds the small string of "Hello World" in each of the 5 records hangs my 64-bit, Windows 7 machine with 8GB RAM and I have to kill julia.exe from Task Manager (which takes about 5 minutes just to get into to kill the hung julia.exe process)

It looks to "immediately" consumes all available physical RAM and then promptly moves over to starting to gobble up additional virtual memory - even after killing Julia.exe, it looks like it takes about 3-4 minutes for my machine to calm down and get back to normal.

**Comment by quinnj** [comment]
An update on this issue:
* whew....it's a tricky one to get right; I've gone through about 3 iterations already trying to get it right
* The problem is it essentially involves allowing a completely separate "result fetching" process than what is currently implemented; non-trivial work to say the least.
* That said, I've tried to put in a few safe-guards, like never fetching more than one row at a time when we're dealing with LONGTEXT type values (NTEXT on SQL Server). This should at least prevent the "blowing up of machines" that was reported elsewhere
* So while we still don't have the ideal solution here, some progress has been made.

**Comment by quinnj** [comment]
Alright, we're now fetching LONGTEXT fields exactly how you're supposed it, only allocating what you need right before fetching. Do let me know if you run into any issues here.
