### ISSUE TITLE
Any way to use 32 bit ODBC sources from 64 bit Julia?

### ISSUE THREAD

**Issue by amellnik** [JuliaDB/ODBC.jl#92]
I noticed that listdns() only shows my 64 bit DSN, presumably because I'm using 64 bit Julia (on Windows).  Is there any way to manually connect to 32 bit sources?

**Comment by quinnj** [comment]
You need to use 32-bit Julia, which you can get from the julialang.org/downloads page.

**Comment by amellnik** [comment]
Hi @quinnj -- would you mind expanding on this a bit?  Is this entirely impossible or just that it would involve handling types differently, or what?  I'm not planning on attempting this this, just curious.  Thanks -A

**Comment by quinnj** [comment]
Sure. 32 vs. 64-bit is a hardware issue. i.e. different physical computers will be built using 32-bit memory addresses or 64-bit memory addresses. Due to this being a physical issue, individual applications are typically built targeting either 32 or 64 bit architectures. They've done this with the Microsoft Office suite, for example, which have 32-bit version as well as 64-bit versions. On latest windows, it actually ships with both 32 and 64-bit versions of the ODBC driver manager. On 64-bit, you can actually run 32-bit **or** 64-bit.

In your case, your machine is 64-bit (by the fact that you can list 64-bit DSN), so it's going to use the 64-bit ODBC library by default. In order to use the 32-bit ODBC library, it's easiest to just use a julia version that was compiled for 32-bit. From the [downloads page](http://julialang.org/downloads/), you'll notice that for windows, it lists both 32-bit and 64-bit versions of julia. You can download and install both simultaneously. Upon starting up 32-bit julia, you can do `Pkg.add("ODBC"); using ODBC` and the library is going to pick up on the 32-bit version of the ODBC driver manager library.

**Comment by amellnik** [comment]
I'm afraid I didn't ask my question very clearly, so let me provide a bit of backstory:  I use some 32-bit enterprise software that talks to both 32- and 64-bit ODBC sources.  Do you have any idea how it might be doing that? The application is 32-bit, so I was wondering if it spawns a 64-bit helper process just to work with the 64 bit sources, or if there's some other standard way of doing this.  I realize this is outside of the scope of ODBC.jl, but was just curious if you had any idea since you've worked extensively with these.

**Comment by quinnj** [comment]
Yeah, I imagine that's how they're managing. Spawn a separate "helper process" that can work with the 32-bit version. You can imagine having a similar "super Julia" which was a master Julia application that could spawn 32-bit or 64-bit versions of julia depending on the libraries that needed loading.
